image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
